apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: conductor
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        client.knative.dev/user-image: "{{IMAGE}}"
        run.googleapis.com/vpc-access-connector: "{{VPC}}"
        run.googleapis.com/vpc-access-egress: all
    spec:
      containers:
        - image: "{{IMAGE}}"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
      serviceAccountName: "{{SERVICE_ACCOUNT}}"
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
