name: Build and Test

on:
  push:
    paths:
      - "src/conductor/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "src/conductor/**"
      - ".github/workflows/ci.yml"

concurrency:
  group: "${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v2

      - name: 🐍 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: setup.py

      - name: 🏗 Install conductor
        run: pip install .[tests,cloud-run]

      - name: 🤐 Create secret file
        run: |
          mkdir -p /secrets/db
          echo "{\"internalsgid\":{}, \"opensgid\":{}, \"github_token\": \"\"}" > /secrets/db/connections

      - name: 🧪 Run pytest
        run: pytest

      - name: ⬆️ Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cov.xml
