name: Build and Test

on:
  push:
    paths:
      - "src/conductor/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "src/conductor/**"
      - ".github/workflows/ci.yml"

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Set up code
        uses: actions/checkout@v2

      - name: 🐍 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 🏗 Install conductor
        run: pip install .[tests,cloud-run]

      - name: 🧪 Run pytest
        run: pytest

      - name: ⬆️ Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cov.xml
