name: "create reminder"

on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: 👁 Monitor permissions
        uses: GitHubSecurityLab/actions-permissions/monitor@v1
        
      - name: 👀 check for reminder
        uses: agrc/create-reminder-action@v1
