name: Pull Request Events

on:
  pull_request:
    paths:
      - "src/conductor/**"
      - ".github/workflows/*.yml"
      - "setup.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: setup.py

      - name: 🏗 Install conductor
        run: pip install .[tests,cloud-run]

      - name: Create folders
        run: mkdir -p secrets/db

      - name: 🤐 Create secret file
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "secrets/db/connections"
          json: ${{ secrets.TESTING_DB_CONNECTIONS }}

      - name: 🧪 Run pytest
        run: pytest

      - name: ⬆️ Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cov.xml
