name: Push Events

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}

    steps:
      - name: 👁 Monitor permissions
        uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - name: 🚀 Create Release
        id: release-please
        uses: agrc/release-composite-action@v1
        with:
          release-type: python
          prerelease: ${{ github.ref_name == 'dev' }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          github-app-id: ${{ secrets.UGRC_RELEASE_BOT_APP_ID }}
          github-app-key: ${{ secrets.UGRC_RELEASE_BOT_APP_KEY }}
          github-app-name: ${{ secrets.UGRC_RELEASE_BOT_NAME }}
          github-app-email: ${{ secrets.UGRC_RELEASE_BOT_EMAIL }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: release-please
    if: github.ref == 'refs/heads/dev' && needs.release-please.outputs.release_created
    environment:
      name: dev
    permissions:
      id-token: write

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v3

      - name: 🚀 Deploy
        uses: ./.github/actions/deploy
        with:
          identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ secrets.PROJECT_ID }}
          vpc: ${{ secrets.VPC }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: release-please
    if: github.ref == 'refs/heads/main' && needs.release-please.outputs.release_created
    environment:
      name: prod
    permissions:
      id-token: write

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v3

      - name: 🚀 Deploy
        uses: ./.github/actions/deploy
        with:
          identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ secrets.PROJECT_ID }}
          vpc: ${{ secrets.VPC }}
